- name: play1
  hosts: prod
  become: true
  vars_files:
    - vault.yaml
  tasks:
    - name: testing package
      dnf:
        name: httpd
        state: present
    - name: enable svc
      service:
        name: httpd
        enabled: true
    - name: start svc
      service:
        name: httpd
        state: started
